src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use App\Service\CartService;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommandeRepository::class)]
class Commande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: '0')]
    private ?string $total = null;

    #[ORM\Column(length: 255)]
    private ?string $etat = null;

    #[ORM\ManyToOne(inversedBy: 'commandes')]
    private ?User $user = null;

    #[ORM\OneToMany(mappedBy: 'commande', targetEntity: Detail::class)]
    private Collection $details;



    public function __construct()
    {
        $this->details = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDatecommande(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDatecommande(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getTotal(): ?string
    {
        return $this->total;
    }

    public function setTotal(string $total): self
    {
        $this->total = $total;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(string $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Detail>
     */
    public function getDetails(): Collection
    {
        return $this->details;
    }

    public function addDetail(Detail $detail): self
    {
        if (!$this->details->contains($detail)) {
            $this->details->add($detail);
            $detail->setCommande($this);
        }

        return $this;
    }

    public function removeDetail(Detail $detail): self
    {
        if ($this->details->removeElement($detail)) {
            // set the owning side to null (unless already changed)
            if ($detail->getCommande() === $this) {
                $detail->setCommande(null);
            }
        }

        return $this;
    }


    
}

src/Controller/CommandeController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Commande;
use App\Repository\CommandeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CommandeController extends AbstractController
{
    #[Route('/admin/commande', name: 'admin_commande')]
    public function commande(CommandeRepository $ripo): Response
    {
        $commande = $ripo->findAll();
        return $this->render('admin/commande/commande.html.twig', [
            'commandes' => $commande,
        ]);
    
    }

    #[Security("is_granted('ROLE_USER') and user === choosenUser")]
    #[Route('/commande/{commande}', name: 'commande_annulee')]
    public function annulee(User $choosenUser, Commande $commande, EntityManagerInterface $em): Response
    {
        $commande->setEtat(4);
        $em->persist($commande);
        $em->flush();
        return $this->redirectToRoute('app_commande', ['id' => $choosenUser->getId()]);
    }
}

templates/commande/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}mes commande {% endblock %}

{% block body %}


<div class="container">
    <h1 class="mt-3">Mes commande</h1>
    <table class="table table-secondary">
        <thead>
            <tr>
                <th scope="col">Numéro</th>
                <th scope="col">Etat</th>
                <th scope="col">Date de commande</th>
                <th scope="col">total a payer</th>
                <th scope="col">Annulée</th>
            </tr>
        </thead>
        <tbody>
            {% for commande in commandes %}
                <tr class="table-dark">
                    <th scope="row">{{ commande.id }}</th>
                    <td>
                        {% if commande.etat == 0 %}
                            Validée
                        {% else %}
                            {% if commande.etat == 1 %}
                                En préparation
                            {% else %}
                                {% if commande.etat == 2 %}
                                    En cours de livraison
                                {% else %}
                                    {% if commande.etat == 3 %}
                                        Livrée
                                    {% else %}
                                        Annulée		
                                    {% endif %}		
                                {% endif %}		
                            {% endif %}
                        {% endif %}
                    <td>{{commande.datecommande|date('d/m/Y')}}</td>
                    <td>{{ commande.total }}€</td>
                    <td>
                        {% if commande.etat != 2 and commande.etat != 3 and commande.etat != 4 %}
                            <a href="{{ path('commande_annulee',{'commande': commande.id}) }}" class="btn btn-info">Annulée</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}